### ISSUE TITLE
Delete the member directory user meta on user delete

### ISSUE THREAD

**Issue by ashubawork** [ultimatemember/ultimatemember#1015]
**Expected behavior**
Delete member directory user meta "um_member_directory_data" on user delete

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Delete user
2. check the user meta "um_member_directory_data" in the database

**Expected behavior**
The user meta "um_member_directory_data" deleted.

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [ ] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce
