### ISSUE TITLE
Form placeholders for custom meta fields are not translated in the members directory search/filter

### ISSUE THREAD

**Issue by docbt** [ultimatemember/ultimatemember#675]
**Expected behavior**
Form placeholders for custom meta fields should be translated in the members directory search/filter

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
In the members directory placeholder for the search/filter input elements are not translated for custom fields. 
The translation in the wpml xml is present, but UM doesn´t translate the placeholders in the members directory.

placeholder = label in the members directory: see class-member-directory.php
`placeholder="placeholder="<?php esc_attr_e( stripslashes( $attrs['label'] ), 'ultimate-member' ); ?>"
						          value="<?php echo esc_attr( $filter_from_url ) ?>" class="um-form-field"
						       aria-label="<?php esc_attr_e( stripslashes( $attrs['label'] ), 'ultimate-member' ); ?>"`

**To Reproduce**
1. add a custom meta field
2. add an filter for the custom meta field in the members directory
3. add an wpml xml translation of the 'label' for a different language
4. open member directory and see the placeholder is not translated

**Expected behavior**
Open the member directory, swicth the language and see translated placeholder.

**Screenshots**

**Do you use UM extensions?**
- [ ] Followers
- [ ] ForumWP
- [ ] Friends
- [x] Google reCAPTCHA
- [ ] Groups
- [ ] Instagram
- [ ] MailChimp
- [ ] myCRED
- [ ] Notices
- [ ] Online Users
- [ ] Private Content
- [ ] Private Messages
- [ ] Profile Completeness
- [ ] Real-time Notifications
- [ ] Social Activity
- [ ] Social Login
- [ ] Terms & Conditions
- [ ] Unsplash
- [ ] User Bookmarks
- [ ] User Photos
- [ ] User Reviews
- [ ] User Tags
- [ ] Verified Users
- [ ] WooCommerce

**WordPress Environment**
Version:	5.5.1
Ultimate Member: 2.1.10
