### ISSUE TITLE
Wrong header meta for the Twitter Card

### ISSUE THREAD

**Issue by nikitasinelnikov** [ultimatemember/ultimatemember#930]
**Expected behavior**
Meta name="twitter:site" must contain the current user username on Twitter but not the blog URL. If there isn't Twitter meta for the user please exclude this not required meta from HEAD

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Ultimate Member plugin is active.
- [x] This bug happens with a default WordPress theme active, or [UM Theme](https://ultimatemember.com/theme/).
- [x] I can reproduce this bug consistently using the steps above.

**Describe the bug**
Meta name="twitter:site" contains the blog URL. There isn't a Twitter account for the website (e.g. @ultimatemember.com)

**To Reproduce**
1. Share the user profile page via Twitter wall

**Screenshots**
https://www.screencast.com/t/OPRNAPDG7
